version: '3'
services:
  app:
    environment:
      SECRET_KEY: ${SECRET_KEY}
    build:
      ./app
    restart: always
    container_name: mon_app
    volumes:
    - ./app/monitorServer:/codigo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "750M"
    networks:
      mon_net:
        ipv4_address: 172.16.10.17



  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80 #se redirige al 80 de nginx
    volumes:
      - ./nginx/cnginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      mon_net:
        ipv4_address: 172.16.10.5

  tty:
    build: ./apptty
    ports:
      - 8888:7681
    networks:
       mon_net:
         ipv4_address: 172.16.10.2
    depends_on:
      - nginx



#Red manual
networks:
  mon_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.10.0/24"
